### ISSUE TITLE
can `mockthat` be used to check messages about conditionally used packages

### ISSUE THREAD

**Issue by IndrajeetPatil** [nbenn/mockthat#3]
If I am conditionally using a package, [for example](https://github.com/IndrajeetPatil/statsExpressions/blob/03f0a38e381aee9c41cc72e73911ab5de126c592/R/oneway_anova.R#L197-L198) `afex`, I would like to write a unit test to cover the following line of code:      

```r
# check if `afex` is installed
if (!requireNamespace("afex", quietly = TRUE)) stop("Package 'afex' needs to be installed.")
```

The problem is that all continuous integration platforms download the suggested packages and so this package is never _not_ available and, as a result, any unit test covering this line of code will be irrelevant.

Is it possible to use `mockthat` to mock removal of `afex` package and write a unit test to check if the error `"Package 'afex' needs to be installed."` is printed?

**Comment by nbenn** [comment]
Sorry for my slow response. I guess the answer to your question is: kind of.

You cannot directly stub out `requireNamespace()`, as this is a function of base. You can however define a function in your package that wraps `requireNamespace()` and then you can stub out that function. Something along the lines of

```r
require_ns <- function(...) requireNamespace(...)

my_fun <- function() {

  if (require_ns("afex", quietly = TRUE)) {
    "yup"
  } else {
    "nope"
  }
}

# in a test
expect_identical(
  with_mock(require_ns = FALSE, my_fun()),
  "nope"
)
```

Functions from packages with `priority = "base"` in the `installed.packages()` sense cannot be mocked with the current implementation. This was also a limitation of the original testthat implementation, but can be worked around with approaches such as the above.

**Comment by IndrajeetPatil** [comment]
Thanks a lot for the detailed reply with an example.

Will try this and revisit if it doesn't work for some reason.
