### ISSUE TITLE
can't mock httr functions importedFrom in a function

### ISSUE THREAD

**Issue by brianrepko** [nbenn/mockthat#5]
@nbenn - I can see your closed issue on this and have looked through the package level tests on utils but I can't get this to work with httr and figured I'd log the issue.

In my package, I have an un-exported function
```
#' @importFrom httr GET authenticate content
authenticate_token <- function(credentials) {
  url <- "https://example.com/authenticate/"
  token <- content(GET(url, authenticate(credentials$username, credentials$password)))
  if (!validate(token)) {
    stop("Error obtaining authentication token")
  }
  return(token)
}
```

in my test, I'm trying to do the following:
```
test_that("authenticate_token: valid credentials supplied", {
  cred <- list(username = dummy_user, password = dummy_password)
  auth <- mockthat::with_mock(
    `httr::content` = function() list(
      user = toupper(dummy_user), 
      url = dummy_url, 
      sessionId = dummy_sessionId, 
      sessionExpiration = dummy_sessionExpiration),
    authenticate_token(cred)
  )
  expect_equal(auth$user, toupper(dummy_user))
  expect_equal(auth$url, dummy_url)
  expect_equal(auth$sessionId, dummy_sessionId)
  expect_equal(auth$sessionExpiration, dummy_sessionExpiration)
})

```
This does not do the actual mocking in this case - it tries to hit the URL and errors out (credentials are not actually valid)
However, if I change the code to use `httr::content`, `httr::GET`, `httr::authenticate` then it works.
It doesn't seem to matter if `authenticate_token` is exported or not (just tried).
I've also tried with "content" and a mock_env of "httr" as well as just returning the list vs a function that returns the list.
I just can't seem to get it to mock if the authenticate code doesn't have the fully qualified function name.
This is my first test of mockthat vs mockery / mockr so trying to work this out before I have to change a bunch of code.

**Comment by brianrepko** [comment]
oh - sorry - I should mention that this is R 3.6.1 and mockthat 0.2.6 - behavior is the same regardless of running `devtools::test()` or RStudio "Run Tests" functionality.

**Comment by nbenn** [comment]
@brianrepko Thanks for raising the issue. I'm happy to check it out as it looks like this should work.

**Comment by brianrepko** [comment]
Playing around via `rlang` env functions
```
mock_content <- function(...) { return(list(....)) }

import_env <- rlang::ns_imports_env('mypackage')
rlang::env_bind(.env = imports_env, content = mock_content)
authenticate_token(list(...)) # gets me the mock token
rlang::env_bind(.env = imports_env, content = httr::content)

httr_env <- rlang::ns_env('httr')
rlang::env_bind(.env = httr_env, content = mock_content)
Error in rlang::env_bind(.env = httr_env, content = mock_content) : 
  cannot change value of locked binding for 'content'
rlang::env_binding_unlock(env = httr_env, nms = 'content')
rlang::env_bind(.env = httr_env, content = mock_content)
authenticate_sdw(list(user_521='test',password='test')) # fails - tries to make call

rlang::env_get(env=imports_env, 'content') # displays original httr::content code
rlang::env_get(env=httr_env, 'content') # displays mock_content code
```
I know you probably don't want the dependency on `rlang` but that might be better than `utils::assignInNamespace`.
The other option for a mocking library would be `base::trace` and `base::untrace`.

**Comment by brianrepko** [comment]
haha - ok this did work
```
test_that("authenticate_token: valid credentials supplied", {
  cred <- list(username = dummy_user, password = dummy_password)
  auth <- mockthat::with_mock(
    `mypackage::content` = function() list(
      user = toupper(dummy_user), 
      url = dummy_url, 
      sessionId = dummy_sessionId, 
      sessionExpiration = dummy_sessionExpiration),
    authenticate_token(cred)
  )
  expect_equal(auth$user, toupper(dummy_user))
  expect_equal(auth$url, dummy_url)
  expect_equal(auth$sessionId, dummy_sessionId)
  expect_equal(auth$sessionExpiration, dummy_sessionExpiration)
})
```
When using `mypackage::content` vs `httr::content` it picks up the import namespace binding for content.
I'm not sure if that is the intent however - that would be an odd syntax.

If you look in the namespace environment of the package, it's parent (imports:package), and then base - there are only ever three for the namespace environments, I believe, then you could do the mocking based on its location. For the import namespace you can check if identical to the actual function (or the namespace is for the other package).

**Comment by brianrepko** [comment]
and heads up - I was able to rebind base::file.exists with the rlang functions - so you should be able to even do base package overrides

**Comment by nbenn** [comment]
@brianrepko Please apologize my slow response.

Having a closer look at the issue you raise, this is both expected and intended. I'm sorry I did not see this when I only had a brief look a couple of days ago. If you check out examples in tests (it's a bit hidden away, I do have to say), we have

https://github.com/nbenn/mockthat/blob/7b4fbd70129b1fa6a45af663cab598d8bfcfdf05/inst/testdata/mocktest/R/funs.R#L73-L84

and then

https://github.com/nbenn/mockthat/blob/7b4fbd70129b1fa6a45af663cab598d8bfcfdf05/tests/testthat/test-mocktest.R#L262-L284

The key here being to specify the function to be mocked in the same way you would in your package code. Consequently, if you import `content()`, prefixing it with `httr::` in the call to `with_mock()` will not work for the reasons you found. I will improve the documentation as it does not say this explicitly anywhere. Thanks for raising the issue!

Regarding rlang: Thank you for brining this to my attention. I am not at all opposed to depending on rlang if this is a way out of using `utils::assignInNamespace()`, as in the docs, R core say

> [This] should not be used in production code

While for now, CRAN have allowed this, it is a bit of an issue with mockthat. I'll definitely try out your suggestion. Thanks again!
